#!/bin/bash
#azure login
#azure config mode arm
{ ## Save all the output for later please
# source the parameters file
. ./$1

echo Deleting everything in resource group is $rg
echo ------------------------------------------------------------------------------
date

azure vm delete $rg $vm2name -q
azure vm delete $rg $vm1name -q
azure network nic delete $rg $vm2nic -q
azure network nic delete $rg $vm1nic -q
azure network vnet subnet delete $rg $vnet $subnetname -q
azure network public-ip delete $rg $vm1publicipname -q
azure network nsg delete $rg $nsgname -q
azure network route-table delete $rg $routetable -q
azure network vnet delete $rg $vnet -q
azure storage account delete $storageaccount -g $rg -q
azure group delete $rg $location -q

echo All done, if the God of Demos has been kind
echo -------------------------------------------
date

} 2>&1 | tee -a $2
